title: Yanxu Mao's Homepage
page-top-title: Yanxu Mao
top-section-bg-text: Yanxu Mao's Homepage
home-subtitle: Yanxu Mao&ensp;|&ensp;毛研旭
copyright-text: '&copy; Yanxu Mao 2023-2026. All Rights Reserved.'
